version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    restart: unless-stopped